### ISSUE TITLE
Cambiar el orden de los campos en Semilla mejorada

### ISSUE THREAD

**Issue by andreadruiz** [gcoop-libre/bioleft#25]
> En Añadir semillas mejoradas, la especie no debería ir después del poder germinativo, sino ser el primer dato y en todos los casos obligatorio

**Comment by andreadruiz** [comment]
https://plataforma.bioleft.org/admin/structure/semilla/add/mis_semillas

**Comment by federmza06** [comment]
Se agrego el field group y se agrego los 2 campos importantes y ordenados al principio del formulario.

**Comment by andreadruiz** [comment]
Adjunto captura de la solución: 
![Screenshot Añadir Mis semillas Bioleft](https://user-images.githubusercontent.com/16581329/71848727-16e8ff80-30af-11ea-97a2-146b01b57f42.png)

**Comment by andreadruiz** [comment]
Adjunto captura de formulario de Semilla Sin registrar.
![Screenshot Añadir Mis semillas Bioleft - sin registrar](https://user-images.githubusercontent.com/16581329/71848807-4435ad80-30af-11ea-8c3a-53f08ded7049.png)
