### ISSUE TITLE
Cambiar términos opcionales para quien es el owner de "Mis semillas", y no al revés

### ISSUE THREAD

**Issue by andreadruiz** [gcoop-libre/bioleft#26]
> Los términos opcionales de las transacciones son para el que da, no para el que recibe, por lo que tendrian que aparecer donde aparecen las licencias

**Comment by andreadruiz** [comment]
Una posibilidad es sacar los campos field_terminos_opcionales y field_terminos y colocarlos en la entidad Mis semillas, para que cuando la semilla esté disponible en la plataforma, quien la solicite, pueda leer los términos y condiciones que ofrece el/la owner de la semilla, y aceptar o rechazar sus terminos. 
La función de la transacción entonces es la de tener el campo Estado y Fecha, eliminandose los campos de field_terminos_opcionales y field_terminos. 
Hay que hacer hooks para que también eso se aplique a transacciones ya realizadas en la plataforma.

**Comment by federmza06** [comment]
La solución que planteamos, es crear los campos field_terminos_opcionales y field_terminos, en la entidad mis_semillas. Cuando el usuario solicite una transacción, se completaran los campos de transacción con los valores almacenados en mis_semillas.
Esto permitirá que si luego el propietario de la semilla cambiar sus términos, la transacción siga almacenando los términos establecidos en el momento de la transacción.
También se soluciona la lógica que el usuario propietario de la semilla pueda crear sus propios términos para poner a disposición la misma mediante la plataforma Bioleft.

**Comment by andreadruiz** [comment]
Adjunto captura de los términos opcionales, ahora presentes en Mis semillas: 

![terminos opcionales Añadir Mis semillas Bioleft](https://user-images.githubusercontent.com/16581329/71918152-7521eb00-3160-11ea-8120-fd1bedee93d7.png)
