### ISSUE TITLE
Captcha deja de aparecer luego de tres intentos fallidos

### ISSUE THREAD

**Issue by andreadruiz** [gcoop-libre/bioleft#27]
> Después de 3 intentos fallidos de iniciar sesión el CAPTCHA desaparece y aún así se puede iniciar sesión

**Comment by andreadruiz** [comment]
Link: https://plataforma.bioleft.org/user/

**Comment by federmza06** [comment]
El problema desaparece al cambiar la configuración del modulo CAPTCHA. (admin/config/people/captcha).
En "Persistence" seleccionar "Always add a challenge".
